=encoding utf8

=head1 NAME

Mojolicious::Plugin::AdvancedMod - More buns for Mojolicious

=head1 SYNOPSIS

  # Load all AdvancedMod Plugins
  $self->plugin('AdvancedMod');

=head1 SEE ALSO

=over 2

=item

L<Mojolicious::Plugin::AdvancedMod::ActionFilter>

=item

L<Mojolicious::Plugin::AdvancedMod::HashedParams>

=item

L<Mojolicious::Plugin::AdvancedMod::Configurator>

=item

L<Mojolicious::Plugin::AdvancedMod::FormHelpers>

=item

L<Mojolicious::Command::am>

=item

https://github.com/grishkovelli/Mojolicious-Plugin-AdvancedMod

=back

=head1 AUTHOR

Grishkovelli L<grishkovelli@gmail.com>

=head1 COPYRIGHT

Copyright (C) 2013, 2014
Grishkovelli L<grishkovelli@gmail.com>

=head1 LICENSE

This module is free software; you can redistribute it and/or modify it under the same terms as Perl itself.

=cut